// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package pg

import (
	"context"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (name, nim)
VALUES ($1, $2)
RETURNING id, name, nim
`

type CreateStudentParams struct {
	Name string
	Nim  string
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, createStudent, arg.Name, arg.Nim)
	var i Student
	err := row.Scan(&i.ID, &i.Name, &i.Nim)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT id, name, nim FROM students
ORDER BY name
`

func (q *Queries) ListStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(&i.ID, &i.Name, &i.Nim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
